[project]
name = "theatremix"
version = "0.1.0"
description = "TheatreMix functions for python"
readme = "README.md"
authors = [{ name = "Harpo", email = "harpo@harpo.me" }]
requires-python = ">=3.10"
dependencies = ["screenplay-tools>=0.0.10", "showrunner", "sqlmodel>=0.0.27"]

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
showrunner = { path = "../ShowRunner", editable = true }

[project.entry-points.showrunner]
theatremix = "theatremix.showrunner:plugin"

[dependency-groups]
dev = ["ipykernel>=7.1.0", "pytest>=9.0.2"]
